from enum import IntEnum

BY_PLANE = True  # Set to True to enable plane-based filtering in bounding box filter
BUTTON_PADDING = 12
FRAME_WIDTH = 700
PADDING = 10
FULL_WIDTH = FRAME_WIDTH - PADDING
FRAME_HEIGHT = 850
FONT_FAMILY = 'Roboto'
FONT_SIZE = 12
FONT_WEIGHT = 'bold'
TEXT_FIELD_WIDTH = 680
TEXT_FIELD_HEIGHT = 130
LARGE_BUTTON_WIDTH = 380
SMALL_BUTTON_WIDTH = 200
BUTTON_HEIGHT = 35
PADDING_X = 20

class Size(IntEnum):
  ONE_THIRD = FULL_WIDTH // 3
  HALF = FULL_WIDTH // 2
  TWO_THIRDS = FULL_WIDTH * 2 // 3
  FULL = FULL_WIDTH

class Status(IntEnum):
  FINISHED = 0
  IN_PROGRESS = 1
  ERROR = 2
