# Style constants
BUTTON_PADDING = 12
FRAME_WIDTH = 700       # Wider frames for better spacing
FRAME_HEIGHT = 850      # Taller frames
FONT_FAMILY = "Roboto"  # Modern Google font
FONT_SIZE = 12
FONT_WEIGHT = 'bold'
TEXT_FIELD_WIDTH = 680
TEXT_FIELD_HEIGHT = 150
LARGE_BUTTON_WIDTH = 380
SMALL_BUTTON_WIDTH = 200
BUTTON_HEIGHT = 35
PADDING_X = 20
